version: 2
jobs:
  test:
    docker:
      - image: validator/validator
    steps:
      - checkout
      - run: scripts/test.sh
  deploy:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Deploying to cloud.gov.au
          command: ./scripts/deploy.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
